name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pre-CI actions
        run: cp ./ci/mock-google-services.json ./app/google-services.json

      - name: KtLint check
        run: ./gradlew ktlint

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          script: ./gradlew connectedDebugAndroidTest
